spring:
  aop:
    auto: true
    proxy-target-class: false
  messages:
    always-use-message-format: false
    basename: messages
  mvc:
    dispatch-options-request: true
    dispatch-trace-request: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: true


  banner:
    location: classpath:banner.txt

  datasource:
    url : jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
  
  jpa:
    show-sql : true
    hibernate:
      ddl-auto : update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:  
        dialect : org.hibernate.dialect.MySQL8Dialect




        
    